title: "Demo page"
url: "https://HyeonjinCha.github.io"
baseurl: ""       # User Page면 빈 문자열
theme: minima     # 공식 Minima 테마 사용
markdown: kramdown
kramdown:
  input: GFM

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed